package tarea_02;

import tarea_02.Mesa.Ingrediente;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 * Esta clase contendrá un panel con un botón que al pusarlo deshabilitará el 
 * botón, instanciará los 3 fumadores y ejecutará el dispensador. Cuando los
 * fumadores hayan acabado, el botón se habilitará de nuevo y mostrará un
 * mensaje al usuario.
 *
 */
public class Main extends javax.swing.JFrame {
    
    // Declaración de atributos
    private static final ArrayList<Fumador> fumadores = new ArrayList<>();
    private Dispensador dispensador;
    private Mesa mesa;

    /**
     * Constructor de la clase, crea el formulario y ajusta la ventana.
     */
    public Main() {
        initComponents();
        
        // Centrar el programa.
        setLocationRelativeTo(null);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalJPanel = new javax.swing.JPanel();
        comenzarJButton = new javax.swing.JButton();
        fumador1JLabel = new javax.swing.JLabel();
        fumador2JLabel = new javax.swing.JLabel();
        fumador3JLabel = new javax.swing.JLabel();
        cigarrillos1JLabel = new javax.swing.JLabel();
        cigarrillos3JLabel = new javax.swing.JLabel();
        cigarrillos2JLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        comenzarJButton.setText("Comenzar");
        comenzarJButton.setToolTipText("");
        comenzarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comenzarJButtonActionPerformed(evt);
            }
        });

        fumador1JLabel.setText("Fumador 1");
        fumador1JLabel.setOpaque(true);

        fumador2JLabel.setText("Fumador 2");
        fumador2JLabel.setOpaque(true);

        fumador3JLabel.setText("Fumador 3");
        fumador3JLabel.setOpaque(true);

        cigarrillos1JLabel.setText("Cigarros");

        cigarrillos3JLabel.setText("Cigarros");

        cigarrillos2JLabel.setText("Cigarros");

        javax.swing.GroupLayout principalJPanelLayout = new javax.swing.GroupLayout(principalJPanel);
        principalJPanel.setLayout(principalJPanelLayout);
        principalJPanelLayout.setHorizontalGroup(
            principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fumador1JLabel)
                    .addComponent(cigarrillos1JLabel))
                .addGap(48, 48, 48)
                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fumador2JLabel)
                    .addComponent(cigarrillos2JLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cigarrillos3JLabel)
                    .addComponent(fumador3JLabel))
                .addContainerGap())
            .addGroup(principalJPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(comenzarJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        principalJPanelLayout.setVerticalGroup(
            principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fumador1JLabel)
                    .addComponent(fumador2JLabel)
                    .addComponent(fumador3JLabel))
                .addGap(18, 18, 18)
                .addGroup(principalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cigarrillos1JLabel)
                    .addComponent(cigarrillos2JLabel)
                    .addComponent(cigarrillos3JLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(comenzarJButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(principalJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(principalJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción al pulsar el botón de comenzar. Deshabilita el botón y ejecuta a
     * los fumadores y el dispensador.
     *
     * @param evt el evento del botón pulsado.
     */
    private void comenzarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comenzarJButtonActionPerformed
        // Deshabilitar botón.
        toggleComenzarJButton(false);

        // Instanciamos los fumadores y la mesa.
        mesa = new Mesa();
        fumadores.add(new Fumador("Fumador 1", mesa, Ingrediente.CERILLAS));
        fumadores.add(new Fumador("Fumador 2", mesa, Ingrediente.PAPEL));
        fumadores.add(new Fumador("Fumador 3", mesa, Ingrediente.TABACO));
        dispensador = new Dispensador(mesa);

        // Inicializamos los hilos.
        fumadores.forEach((fumador) -> {
            fumador.start();
        });

        dispensador.start();
    }//GEN-LAST:event_comenzarJButtonActionPerformed

    /**
     * Activa o desactiva el botón de comenzar del programa.
     *
     * @param activo true para activarlo, false para desactivarlo.
     */
    public static void toggleComenzarJButton(boolean activo) {
        comenzarJButton.setEnabled(activo);
    }

    /**
     * Devuelve el array de fumadores activos.
     *
     * @return ArrayList fumadores activos.
     */
    public static ArrayList<Fumador> getFumadores() {
        return fumadores;
    }

    /**
     * Devuelve el label que representa a los cigarrillos del fumador 1.
     *
     * @return JLabel cigarrilos restantes del fumador 1.
     */
    public static JLabel getCigarrillos1JLabel() {
        return cigarrillos1JLabel;
    }

    /**
     * Devuelve el label que representa a los cigarrillos del fumador 2.
     *
     * @return JLabel cigarrilos restantes del fumador 3.
     */
    public static JLabel getCigarrillos2JLabel() {
        return cigarrillos2JLabel;
    }

    /**
     * Devuelve el label que representa a los cigarrillos del fumador 3.
     *
     * @return JLabel cigarrilos restantes del fumador 3.
     */
    public static JLabel getCigarrillos3JLabel() {
        return cigarrillos3JLabel;
    }

    /**
     * Devuelve el label que representa al fumador 1.
     *
     * @return JLabel label que representa al fumador 1.
     */
    public static JLabel getFumador1JLabel() {
        return fumador1JLabel;
    }

    /**
     * Devuelve el label que representa al fumador 2.
     *
     * @return JLabel label que representa al fumador 2.
     */
    public static JLabel getFumador2JLabel() {
        return fumador2JLabel;
    }

    /**
     * Devuelve el label que representa al fumador 3.
     *
     * @return JLabel label que representa al fumador 3.
     */
    public static JLabel getFumador3JLabel() {
        return fumador3JLabel;
    }
    
    /**
     * Cambia el texto de un label para que muestre el número de cigarrillos
     * restante.
     *
     * @param label a editar el texto.
     * @param cigarrillos restantes a mostrar.
     */
    public static void setText(JLabel label, int cigarrillos) {
        label.setText("Cigarros: " + cigarrillos);
    }
    
    /**
     * Cambia el color de fondo de un label para indicar si está activo o no.
     *
     * @param label a editar el color de fondo.
     * @param color al que cambiará el JLabel
     */
    public static void setBackground(JLabel label, Color color) {
        label.setBackground(color);
    }
    
    /**
     * Constructor con argumentos pasados por parámetros.
     *
     * @param args los comandos pasados por parámetros.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel cigarrillos1JLabel;
    private static javax.swing.JLabel cigarrillos2JLabel;
    private static javax.swing.JLabel cigarrillos3JLabel;
    private static javax.swing.JButton comenzarJButton;
    private static javax.swing.JLabel fumador1JLabel;
    private static javax.swing.JLabel fumador2JLabel;
    private static javax.swing.JLabel fumador3JLabel;
    private javax.swing.JPanel principalJPanel;
    // End of variables declaration//GEN-END:variables
}
